# Generated by Django 3.2.5 on 2021-07-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatternTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
