# Generated by Django 3.2.5 on 2021-07-30 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_auto_20210730_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterntable',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns_incategory', to='patterns.category'),
        ),
    ]
